- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  tasks:

    - name: Disable swap
      shell: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Disable swap in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Add Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      register: docker_repo

    - name: Add Kubernetes apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      register: kubernetes_repo

    - name: Update apt cache
      apt:
        update_cache: yes
      when: docker_repo is changed or kubernetes_repo is changed

    - name: Install containerd, Docker and Kubernetes
      apt:
        name:
          - containerd.io={{ containerd_version }}
          - docker-ce={{ docker_version }}
          - kubelet={{ kubelet_version }}
          - kubeadm={{ kubeadm_version }}
          - kubectl={{ kubectl_version }}
        state: present

    - name: Hold containerd
      dpkg_selections:
        name: containerd.io
        selection: hold

    - name: Hold Docker
      dpkg_selections:
        name: docker-ce
        selection: hold

    - name: Hold Kubelet
      dpkg_selections:
        name: kubelet
        selection: hold

    - name: Hold Kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Hold Kubectl
      dpkg_selections:
        name: kubectl
        selection: hold

    - name: Make sure a Docker service is running and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Configure Docker daemon
      copy:
        src: files/docker-daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
      register: docker_daemon_config

    - name: Restart Docker daemon if config has changed
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
      when: docker_daemon_config.changed

    - name: Install nfs-common to support NFS provisioner
      apt:
        name: nfs-common

    - name: Install Kernel headers to support Falco
      apt:
        name: "linux-headers-{{ ansible_kernel }}"
